### ISSUE TITLE
what is your spatial compression ?

### ISSUE THREAD

**Issue by almfahd41** [gnobitab/InstaFlow#1]
hello 

for example  the Würstchen v2 is 42x spatial compression

![F57OPLsWUAADemz](https://github.com/gnobitab/InstaFlow/assets/111824871/46a3f6ff-c630-45e5-a93d-c5238af7bb87)

**Comment by gnobitab** [comment]
Hi, thank you for asking! We use exactly the same pipeline as Stable Diffusion, so the spatial compression is 8 $\times$ (the latent is 64 $\times$ 64). This is also in the Appendix I remember.
