### ISSUE TITLE
Question about understanding of this tech

### ISSUE THREAD

**Issue by isamu-isozaki** [gnobitab/InstaFlow#12]
Hi! Thanks for the awesome paper and impressive results! I have one question about the training process.
When we are predicting velocity in say sd1.4, the usual objective is just epsilon but do you do some transformation to make it v or do you have the network predict v immediately? Thanks! 
Also, I made a blog [here](https://huggingface.co/blog/Isamu136/insta-rectified-flow) talking about the paper+plans to make it a diffuser pr. The plan I currently have is
- [ ] Make a script to generate the latent noise, images, and text to save to the dataset
- [ ] Make rectified flow/reflow script
- [ ] Make distillation script

**Comment by gnobitab** [comment]
We have the network to predict v directly, as can be found in the inference code.

Thank you for the blog and your contribution!
