### ISSUE TITLE
source code and model MUST BE RELEASED IMMEDIATELY

### ISSUE THREAD

**Issue by spacewalkingninja** [gnobitab/InstaFlow#13]
THIS IS AN ORDER, EFFECTIVE NOW,
AS TITLE SAYS
DO NOT WAIT ANYMORE!!!!
I (I AM GOD BTW!!!)) so where i was... I AM DIRECTLY GIVING THIS AS A ORDER!!!

**Comment by spacewalkingninja** [comment]
@gnobitab @lqiang67 thanks from god <3 heheheheh and btw consider urself lucky u have spoken 2 god hihihihi <3 NOW RELEASE THE CODE!!! AND MODELS!!!! COMMERCIAL FREE RIGHT NOW ASAP!!!! I, GOD, NEED IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!
idk how 2 explain this ANY more obvious LOL

**Comment by spacewalkingninja** [comment]
Hello!!! GOD IS DELIVERING AN IMMEDIATE ORDER!!!

> RELEASE THE code **_NOW!!!!_**

**Comment by spacewalkingninja** [comment]
**_### GOD_** is kindly asking **WHERE** the source code IS

**Comment by danieltanhx** [comment]
no point pushing him, can follow up in https://github.com/huggingface/diffusers/pull/5397

**Comment by isamu-isozaki** [comment]
Hi! For people interested in reproduction, I am almost done with a PR https://github.com/huggingface/diffusers/pull/5397 but I'm lacking compute for testing a minimal version so if anyone is interested in running the [Google collab](https://colab.research.google.com/drive/13GmggtFLnVj55i2XnVp-E_-tLgv2ThSm#scrollTo=Mig5wVWoKspI) /run the code on their hardware that would be a great help!

Also, ideas on how to improve this code are very welcome!

**Comment by spacewalkingninja** [comment]
@gnobitab this is your GODS speaking!!!!!!!!!!!!!!!!!!!!!!!!!!! WE NEED THE MODEL RELEASED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! AND THE CODE!!!!!!!!!!!!!!!!!!!!!!!!! YOU MUST DO IT!!!!!!!!!!!!!!!!!! TODAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
