### ISSUE TITLE
ONNX converted model, Windows UI support

### ISSUE THREAD

**Issue by saddam213** [gnobitab/InstaFlow#20]
We have converted both models to ONNX format and have added initial support for InstaFlow to OnnxStack

ONNX Model
https://huggingface.co/TheyCallMeHex/InstaFlow-0.9B-ONNX/tree/main
https://huggingface.co/TheyCallMeHex/2-Rectified-Flow-ONNX

OnnxStack UI download (windows only)
https://github.com/saddam213/OnnxStack/releases/tag/v0.9.1-pre

InstaFlow-0.9B | 1 Step
![image](https://github.com/gnobitab/InstaFlow/assets/4353684/a8cd7400-75ee-4f5a-98c8-832e47e2c7e0)

**Comment by gnobitab** [comment]
Thank you so much! I will check and add that to the README of the repo!

**Comment by saddam213** [comment]
We now support the Rectified low step models
https://github.com/saddam213/OnnxStack/releases/tag/v0.10.0

**Comment by gnobitab** [comment]
Thank you! I will add these links to README.
