### ISSUE TITLE
Reuqest: BETTER FREE MODEL COMMERCIAL AVAILABLE!!!! FOR POOR PEOPLE!!!!

### ISSUE THREAD

**Issue by spacewalkingninja** [gnobitab/InstaFlow#21]
I cant train a model, i only got a 1070ti, I BEG YOU TO RELEASE COMMERCIAL MODEL TODAY!!!!!!! OR I WILL OFF MYSELF I AM

**Comment by spacewalkingninja** [comment]
I'm very poor I can't use your software please I don't know what to do anymore on this planet please I BEG YOU

**Comment by gnobitab** [comment]
This is a decision by the company, not by me. Please stop being troll on the internet.
