### ISSUE TITLE
I think the author is more likely not to release the training code and pre trained models

### ISSUE THREAD

**Issue by YangPanHZAU** [gnobitab/InstaFlow#8]
The reasons are as follows:
I am a worker in the field of the acceleration inference step in text-to-image diffuison, the similarity works such as Snapfusion and W-condition model are not open source currently.
Snapfusion: Text-to-Image Diffusion Model on Mobile Devices within Two Seconds,https://github.com/snap-research/SnapFusion
W-condition: [On Distillation of Guided Diffusion Models](https://arxiv.org/abs/2210.03142) (CVPR 2023, Award candidate).

If the author does not intend to open source the code, I will reproduce the InstaFlow. Could you please communicate with me about the InstaFlow.

**Comment by pietrobolcato** [comment]
Please do! An opensource implementation would be awesome, let us know if we can help!

**Comment by spacewalkingninja** [comment]
Yes this is very interesting! Thanks for contributing!

**Comment by putuoka** [comment]
Don't open source it yet. First create a commercial version that can be sold to companies. After that, you can work on an open source version separately, similar to how StableAudio did their release.

**Comment by spacewalkingninja** [comment]
hello any news, where is the model?

**Comment by spacewalkingninja** [comment]
> Don't open source it yet. First create a commercial version that can be sold to companies. After that, you can work on an open source version separately, similar to how StableAudio did their release.

THIS IS REQUIREMENT BY LAW:
OPEN SOURCE MUST BE RELEASED FIRST ASAP POOR PEOPLE NEED IT AROUND THE WORLD!!!!
POOR PEOPLE CANNOT AFFORD SOFTWARE & HIGH END HARDWARE!!!! THINK OF THEIR NEEDS FIRST BEFORE MULTIMILLION COMPANIES!!!

**Comment by WyattAutomation** [comment]
Yall..  The paper appears to have enough information that even if they don't release it, I would bet money Lucidrains or the OP of this issue will pull through and release a community version.

YangPanHZAU above mentions that "if they don't release it" they are capable of reproducing the paper.  Someone did this for DragGAN and they eventually released that one; think about it for a second--do you want to spend all that effort just to flex your ability to turn a whitepaper into code if they release the full model?

All we need from the Authors is a clear and honest "yes" or "no"; if it is "no" then building a community version makes sense and is well within the ability of at least a couple people in this thread.

Patience is valuable.  With all that said though, I have a proposition to suggest:

Perhaps we set ourselves a "cutoff date", where after that point, if the author has not answered if/when they will release the code/models, we stop waiting and begin work on an Open Source version?

I feel like this should become a more common pattern:

1) Set an agreed upon date amongst potential contributors to start working on a community version, if the author has not updated us on the status of code/model sharing by then

2) Communicate that date to the author of the repo, and let them know that it would be kind of them to give an honest "yes" or "no" on or before that date, or that they can let us know if we should give them more time.  If they need more time, we adjust the start-date of community efforts as needed.  

The author isn't obligated to share anything nor communicate with any of us.  I want access to this code/models too but we can't depend entirely on handouts from funded entities if we want a robust Open Source community.  If you are truly passionate about Democratizing technology, let's express that passion through organization and contribution.

Don't discount the communities ability to provide a solution, and don't disrespect the author for being bound to rules they may not even have any control over.

**Comment by Pevernow** [comment]
@gnobitab If there is still no reply within the next week, we will assume that you are unwilling to provide models and source code, and try to start forging the community version.

**Comment by Pevernow** [comment]
@YangPanHZAU  My abilities are limited, but I would love to write webui for Instaflow.

**Comment by danieltanhx** [comment]
https://github.com/huggingface/diffusers/issues/5256

**Comment by oxysoft** [comment]
This is incredibly important work, with 1 step diffusion we get as many FPS as we get it/s, so we are entering the realm of realtime.

**Comment by gnobitab** [comment]
Code and pre-trained models are released.

**Comment by spacewalkingninja** [comment]
> Code and pre-trained models are released.

NO THEY ARE NOT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IT IS NOT OPEN SOURCE!!!!!!!!!!!!! **OPEN SOURCE COMMUNITY BETRAYAL!!!!!!!!!!!!!!!!!!!!**

**Comment by oxysoft** [comment]
Lol chill, it's right there

* Code https://github.com/gnobitab/InstaFlow/tree/main/code
* Few-step model https://huggingface.co/XCLiu/2_rectified_flow_from_sd_1_5/
* 1 step model https://huggingface.co/XCLiu/instaflow_0_9B_from_sd_1_5

Huge thanks to the author for coming thru, this is gonna be a blast.

**Comment by WyattAutomation** [comment]
I just got ~21 FPS realtime SD + MultiControlNet  working in my app's pipeline because of this.  InstaFlow + DMD = Cookin' with **_gas_**.

https://github.com/user-attachments/assets/239afba6-9a35-4bcc-9a6f-928e92bc8fd1

There are many other optimizations in my pipeline but this was the remaining piece to get it going this fast.  

I have this working with LayerDiffusion as well thanks to @rootonchair and their port of it to SD 1.5 and their assitance in OneDiff [integration](https://github.com/rootonchair/diffuser_layerdiffuse/issues/6#issuecomment-2353064246)   -- that means I should be able to spin up multiple pipelines now and do realtime _composite_ image generation.  Load up a specialized pipeline for any stream of ControlNet elements you want from your game engine of choice.

Next up: going to set up an LLM agent with function calling in Unity to start dropping-in OpenPose enemies and LooseControl cubes..  Fully realtime AI rendered videogame anyone?

It's getting there, thank you **_SO MUCH_** for releasing this!!
